CREATE DATABASE retail_sales_db;

USE retail_sales_db;
show tables;
ALTER TABLE `sql - retail sales analysis`
RENAME TO retail_sales;
describe retail_sales;
ALTER TABLE retail_sales
RENAME COLUMN `ï»¿transactions_id` TO transactions_id;
ALTER TABLE retail_sales
RENAME COLUMN quantiy TO quantity;
SELECT COUNT(*)
FROM retail_sales;
SELECT *
FROM retail_sales
LIMIT 5;
-- Q1: Total Number of Transactions

SELECT COUNT(*)
FROM retail_sales;

-- Q2: Total Revenue

SELECT SUM(total_sale)
FROM retail_sales;

-- Q3: Find the average sale value per transaction

SELECT AVG(total_sale) AS average_sale
FROM retail_sales;

-- Q4: Find the total number of unique customers

SELECT COUNT(DISTINCT customer_id) AS total_customers
FROM retail_sales;

-- Q5: Find all unique product categories available in the dataset

SELECT DISTINCT category AS category
FROM retail_sales;

-- Q6: Calculate total revenue generated by each category

SELECT
    category,
    SUM(total_sale) AS revenue
FROM retail_sales
GROUP BY category
ORDER BY revenue DESC;

-- Q7: Find the category that generated the highest total revenue

SELECT
    category,
    SUM(total_sale) AS revenue
FROM retail_sales
GROUP BY category
ORDER BY revenue DESC
LIMIT 1;

-- Q8: Find the total number of transactions made in each category

SELECT
    category,
    COUNT(transactions_id) AS total_transactions
FROM retail_sales
GROUP BY category
ORDER BY total_transactions DESC;

-- Q9: Find the total revenue generated by Male and Female customers

SELECT
    gender,
    SUM(total_sale) AS revenue
FROM retail_sales
GROUP BY gender
ORDER BY revenue DESC;

-- Q10: Find the average age of customers for each product category

SELECT
    category,
    AVG(age) AS Avg_Age
FROM retail_sales
GROUP BY category
ORDER BY Avg_Age DESC;

-- Q11: Find total revenue generated by each age group

SELECT
    CASE
		WHEN age < 18 THEN 'Under 18'
        WHEN age BETWEEN 18 AND 25 THEN '18-25'
        WHEN age BETWEEN 26 AND 35 THEN '26-35'
        WHEN age BETWEEN 36 AND 50 THEN '36-50'
        ELSE '50+'
    END AS age_group,

    SUM(total_sale) AS revenue

FROM retail_sales

GROUP BY age_group;

-- Q12: Find the Top 5 Customers based on total spending

SELECT
    customer_id,
    SUM(total_sale) AS total_spending
FROM retail_sales
GROUP BY customer_id
ORDER BY total_spending DESC
LIMIT 5;

-- Q13: Find the category with the highest quantity sold

SELECT
    category,
    SUM(quantity) AS total_quantity
FROM retail_sales
GROUP BY category
ORDER BY total_quantity DESC
LIMIT 1;

-- Q14: Find the total quantity sold for each category

SELECT
    category,
    SUM(quantity) AS total_quantity
FROM retail_sales
GROUP BY category
ORDER BY total_quantity DESC;

-- Q15: Find the average quantity purchased per transaction for each category

SELECT
    category,
    AVG(quantity) AS avg_quantity
FROM retail_sales
GROUP BY category
ORDER BY avg_quantity DESC;

DESC retail_sales;

-- Q16: Find the customer with the highest total spending

SELECT
    customer_id,
    SUM(total_sale) AS total_spending
FROM retail_sales
GROUP BY customer_id
ORDER BY total_spending DESC
LIMIT 1;

-- Q17: Find categories with total revenue greater than 150000

SELECT
    category,
    SUM(total_sale) AS revenue
FROM retail_sales
GROUP BY category
HAVING SUM(total_sale) > 150000;

-- Q18: Find categories having more than 600 transactions

SELECT
    category,
    COUNT(transactions_id) AS total_transactions
FROM retail_sales
GROUP BY category
HAVING COUNT(transactions_id) > 600;

-- Q19: Find genders with average revenue greater than 450

SELECT
    gender,
    AVG(total_sale) AS avg_revenue
FROM retail_sales
GROUP BY gender
HAVING AVG(total_sale) > 450;

-- Q20: Find the Top 5 customers by total spending

SELECT
    customer_id,
    SUM(total_sale) AS total_spending
FROM retail_sales
GROUP BY customer_id
ORDER BY total_spending DESC
LIMIT 5;
